export const USER_LOGIN = {
    REQUEST: "USER_LOGIN_REQUEST",
    SUCCESS: "USER_LOGIN_SUCCESS",
    FAIL: "USER_LOGIN_FAIL",
};

export const USER_REGISTER = {
    REQUEST: "USER_REGISTER_REQUEST",
    SUCCESS: "USER_REGISTER_SUCCESS",
    FAIL: "USER_REGISTER_FAIL",
};

export const USER_FETCH = {
    REQUEST: "USER_FETCH_REQUEST",
    SUCCESS: "USER_FETCH_SUCCESS",
    FAIL: "USER_FETCH_FAIL",
};

export const UPDATE_IMAGE = {
    REQUEST: "UPDATE_IMAGE_REQUEST",
    SUCCESS: "UPDATE_IMAGE_SUCCESS",
    FAIL: "UPDATE_IMAGE_FAIL",
};

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_PRAYERS_USER = {
    REQUEST: "GET_PRAYERS_USER_REQUEST",
    SUCCESS: "GET_PRAYERS_USER_SUCCESS",
    FAIL: "GET_PRAYERS_USER_FAIL",
};

export const GET_GALLERY_IMAGES = {
    REQUEST: "GET_GALLERY_IMAGES_REQUEST",
    SUCCESS: "GET_GALLERY_IMAGES_SUCCESS",
    FAIL: "GET_GALLERY_IMAGES_FAIL",
};

export const GET_SCCS = {
    REQUEST: "GET_SCCS_REQUEST",
    SUCCESS: "GET_SCCS_SUCCESS",
    FAIL: "GET_SCCS_FAIL",
};

export const GET_SCC = {
    REQUEST: "GET_SCC_REQUEST",
    SUCCESS: "GET_SCC_SUCCESS",
    FAIL: "GET_SCC_FAIL",
};

export const ADMIN_LOGIN = {
    REQUEST: "ADMIN_LOGIN_REQUEST_LOAD",
    SUCCESS: "ADMIN_LOGIN_SUCCESS_LOAD",
    FAIL: "ADMIN_LOGIN_FAIL_LOAD",
};

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export const ADD_USER = {
    REQUEST: "ADD_USER_REQUEST_LOAD",
    SUCCESS: "ADD_USER_SUCCESS_LOAD",
    FAIL: "ADD_USER_FAIL_LOAD",
};

export const GET_USERS = {
    REQUEST: "GET_USERS_REQUEST_LOAD",
    SUCCESS: "GET_USERS_SUCCESS_LOAD",
    FAIL: "GET_USERS_FAIL_LOAD",
};

export const USERS_SEARCH = {
    REQUEST: "USERS_SEARCH_REQUEST",
    SUCCESS: "USERS_SEARCH_SUCCESS",
    FAIL: "USERS_SEARCH_FAIL",
};

export const GET_ADMINS = {
    REQUEST: "GET_ADMINS_REQUEST_LOAD",
    SUCCESS: "GET_ADMINS_SUCCESS_LOAD",
    FAIL: "GET_ADMINS_FAIL_LOAD",
};

export const CREATE_ADMIN = {
    REQUEST: "CREATE_ADMIN_REQUEST_LOAD",
    SUCCESS: "CREATE_ADMIN_SUCCESS_LOAD",
    FAIL: "CREATE_ADMIN_FAIL_LOAD",
};

export const GET_PRAYERS = {
    REQUEST: "GET_PRAYERS_REQUEST_LOAD",
    SUCCESS: "GET_PRAYERS_SUCCESS_LOAD",
    FAIL: "GET_PRAYERS_FAIL_LOAD",
};

export const CREATE_PRAYER = {
    REQUEST: "CREATE_PRAYER_REQUEST_LOAD",
    SUCCESS: "CREATE_PRAYER_SUCCESS_LOAD",
    FAIL: "CREATE_PRAYER_FAIL_LOAD",
};

export const EDIT_PRAYER = {
    REQUEST: "EDIT_PRAYER_REQUEST_LOAD",
    SUCCESS: "EDIT_PRAYER_SUCCESS_LOAD",
    FAIL: "EDIT_PRAYER_FAIL_LOAD",
};

export const GET_IMAGES = {
    REQUEST: "GET_IMAGES_REQUEST_LOAD",
    SUCCESS: "GET_IMAGES_SUCCESS_LOAD",
    FAIL: "GET_IMAGES_FAIL_LOAD",
};

export const UPLOAD_IMAGE = {
    REQUEST: "UPLOAD_IMAGE_REQUEST_LOAD",
    SUCCESS: "UPLOAD_IMAGE_SUCCESS_LOAD",
    FAIL: "UPLOAD_IMAGE_FAIL_LOAD",
};

export const ADD_SCC = {
    REQUEST: "ADD_SCC_REQUEST_LOAD",
    SUCCESS: "ADD_SCC_SUCCESS_LOAD",
    FAIL: "ADD_SCC_FAIL_LOAD",
};

export const FETCH_EVENTS = {
    REQUEST: "FETCH_EVENTS_REQUEST_LOAD",
    SUCCESS: "FETCH_EVENTS_SUCCESS_LOAD",
    FAIL: "FETCH_EVENTS_FAIL_LOAD",
};

export const FETCH_LEADERS = {
    REQUEST: "FETCH_LEADERS_REQUEST_LOAD",
    SUCCESS: "FETCH_LEADERS_SUCCESS_LOAD",
    FAIL: "FETCH_LEADERS_FAIL_LOAD",
};

export const FETCH_LEADER = {
    REQUEST: "FETCH_LEADER_REQUEST_LOAD",
    SUCCESS: "FETCH_LEADER_SUCCESS_LOAD",
    FAIL: "FETCH_LEADER_FAIL_LOAD",
};

export const UPDATE_LEADER = {
    REQUEST: "UPDATE_LEADER_REQUEST_LOAD",
    SUCCESS: "UPDATE_LEADER_SUCCESS_LOAD",
    FAIL: "UPDATE_LEADER_FAIL_LOAD",
};

export const FETCH_POSITIONS = {
    REQUEST: "FETCH_POSITIONS_REQUEST_LOAD",
    SUCCESS: "FETCH_POSITIONS_SUCCESS_LOAD",
    FAIL: "FETCH_POSITIONS_FAIL_LOAD",
};